adding in custom SQL transformation
onehouseinc/demos pull request #1
Opened 2024-09-30 18:25 UTC by alberttwong

2024-09-30 23:39 UTC, sagarlakshmipathy requested changes

2024-09-30 23:39 UTC, sagarlakshmipathy commented on OnehouseCustomSQLTransformation/src/test/java/SqlQueryBasedTransformerTest.java
> + /*    @BeforeAll
Why did we comment out all the tests?

2024-09-30 23:39 UTC, sagarlakshmipathy commented on OnehouseCustomSQLTransformation/pom.xml
> +        <!-- Hudi Utilities -->
Can we remove the unnecessary items in the pom.xml file?

2024-09-30 23:39 UTC, sagarlakshmipathy commented on OnehouseCustomSQLTransformation/readme.md
> +Onehouse.ai Custom Transformation based on https://docs.onehouse.ai/docs/product/ingest-data/transformations/custom-transformers
Can you add instructions here to use the transformer? 

Like 
1. How to build the jar. Its okay if it is redundant as well. 
2. What properties needs to be added in Onehouse console.

2024-09-30 23:39 UTC, sagarlakshmipathy commented on OnehouseCustomSQLTransformation/target/maven-archiver/pom.properties
> +artifactId=sqltransformer
Can we remove the `target` directory altogether

2024-09-30 23:39 UTC, sagarlakshmipathy commented on OnehouseCustomSQLTransformation/src/test/java/SqlQueryBasedTransformerTest.java
> + /*    @BeforeAll
Can we add one happy path test case doing an in-stream transformation, like adding a column or deriving a column. 
Can we add test cases where we hit the exception and assert it?

2025-04-17 20:25 UTC, alberttwong commented on OnehouseCustomSQLTransformation/src/test/java/SqlQueryBasedTransformerTest.java
> + /*    @BeforeAll
Let's aim to post first and then optimize as time goes on.

2025-04-17 20:26 UTC, alberttwong commented on OnehouseCustomSQLTransformation/pom.xml
> +        <!-- Hudi Utilities -->
Let's aim to post first and then optimize as time goes on.

2025-04-17 20:26 UTC, alberttwong commented on OnehouseCustomSQLTransformation/target/maven-archiver/pom.properties
> +artifactId=sqltransformer
Let's aim to post first and then optimize as time goes on.

2025-04-17 20:26 UTC, alberttwong commented on OnehouseCustomSQLTransformation/readme.md
> +Onehouse.ai Custom Transformation based on https://docs.onehouse.ai/docs/product/ingest-data/transformations/custom-transformers
Let's aim to post first and then optimize as time goes on.

2025-04-17 20:28 UTC, sagarlakshmipathy commented on OnehouseCustomSQLTransformation/readme.md
> +Onehouse.ai Custom Transformation based on https://docs.onehouse.ai/docs/product/ingest-data/transformations/custom-transformers
Can you add more to this?

1. What properties to use to work with this transformer?
2. An example query to pass and a screenshot of the result

2025-04-18 23:10 UTC, closed without merging